const fs = require('fs');
const file = fs.readFileSync('src/data/translations.ts', 'utf8');

const faTranslation = {
  appName: 'دایرکتوری کوثر',
  tagline: 'کسب و کارهای مورد اعتماد شیعه را در نزدیکی خود پیدا کنید',
  subTagline: 'مرور بیش از ۱۰ فروشگاه، خدمات و متخصصین تایید شده.',
  searchPlaceholder: 'جستجوی برق‌کار، رستوران...',
  searchButton: 'جستجو',
  newyork: 'نیویورک',
  losangeles: 'لس آنجلس',
  chicago: 'شیکاگو',
  houston: 'هیوستون',
  miami: 'میامی',
  dearborn: 'دیربورن',
  dallas: 'دالاس',
  allCities: 'همه شهرها',
  categories: 'دسته‌بندی‌ها',
  featured: 'ویژه',
  allBusinesses: 'همه کسب و کارها',
  seeAll: 'مشاهده همه',
  home: 'خانه',
  search: 'جستجو',
  saved: 'ذخیره شده',
  business: 'کسب و کار',
  account: 'حساب کاربری',
  verified: 'تایید شده',
  visitorGreeting: 'سلام علیکم',
  visitorSubtitle: 'جامعه خود را کشف کنید',
  noResults: 'هیچ کسب و کاری مطابق با جستجوی شما یافت نشد.',
  resultsCount: 'نتیجه',
  guestUser: 'کاربر مهمان',
  signInPrompt: 'برای ذخیره علاقه‌مندی‌ها و تماس سریع‌تر وارد شوید.',
  signIn: 'ورود',
  register: 'ثبت نام',
  signOut: 'خروج',
  phone: 'شماره تلفن',
  email: 'آدرس ایمیل',
  password: 'رمز عبور',
  name: 'نام کامل',
  role: 'من هستم یک',
  roleCustomer: 'مشتری (جستجوی کسب و کارها)',
  roleBusiness: 'صاحب کسب و کار (ثبت کسب و کار من)',
  continueAsGuest: 'ادامه به عنوان مهمان',
  createAccount: 'ایجاد حساب کاربری',
  alreadyHaveAccount: 'قبلا ثبت نام کرده‌اید؟ ورود',
  noAccountYet: 'کاربر جدید هستید؟ ثبت نام',
  businessPortal: 'پورتال کسب و کار',
  portalSub: 'مدیریت لیست شما',
  adminPanel: 'پنل مدیریت',
  adminSub: 'دسترسی محدود',
  notifications: 'اعلان‌ها',
  noNotifications: 'هنوز اعلانی ندارید.',
  markAllRead: 'علامت‌گذاری همه به عنوان خوانده شده',
  clearAll: 'پاک کردن همه',
  privacy: 'حریم خصوصی',
  ownerName: 'نام صاحب کسب و کار',
  businessName: 'نام کسب و کار',
  description: 'توضیحات',
  address: 'آدرس',
  website: 'وب‌سایت (اختیاری)',
  whatsapp: 'شماره واتس‌اپ',
  workingHours: 'ساعات کاری',
  selectCategory: 'انتخاب دسته‌بندی',
  active: 'فعال',
  suspended: 'معلق / قفل شده',
  membershipStatus: 'وضعیت عضویت',
  memberExpiry: 'عضویت شما فعال است تا',
  memberSuspended: 'حساب شما معلق شده است. لطفا عضویت خود را تمدید کنید.',
  renewMembership: 'تمدید عضویت (۵۰ دلار/ماه)',
  renewDescription: 'با تمدید عضویت، کسب و کار شما در ۳۰ روز آینده در معرض دید قرار گرفته و مشتریان می‌توانند مستقیما با شما تماس بگیرند.',
  paymentGateway: 'پرداخت آنلاین',
  cardNumber: 'شماره کارت',
  cardExpiry: 'ماه / سال',
  cardCVC: 'کد امنیتی (CVC)',
  processPayment: 'پرداخت ۵۰ دلار اکنون',
  paymentHistory: 'تاریخچه پرداخت',
  totalRevenue: 'مجموع درآمد',
  amount: 'مبلغ',
  date: 'تاریخ',
  refNo: 'شماره پیگیری',
  registerBusiness: 'ثبت کسب و کار جدید',
  submitApplication: 'ارسال درخواست',
  allFieldsRequired: 'لطفا تمام فیلدهای الزامی را پر کنید.',
  logoUrl: 'لینک تصویر لوگو (اختیاری)',
  coverUrl: 'لینک تصویر کاور (اختیاری)',
  registeredSuccessfully: 'درخواست ثبت کسب و کار ارسال شد! در انتظار تایید مدیریت.',
  adminTitle: 'مدیریت پلتفرم',
  approve: 'تایید',
  reject: 'رد',
  suspendFlag: 'معلق کردن',
  activateFlag: 'فعال کردن',
  users: 'کاربران',
  reports: 'گزارش‌ها',
  payments: 'پرداخت‌ها',
  contactBusiness: 'تماس با کسب و کار',
  whatsappMessage: 'سلام، من کسب و کار شما را در دایرکتوری شیعیان پیدا کردم و می‌خواهم در مورد خدمات شما بپرسم.',
  callNow: 'تماس بگیرید',
  openWhatsapp: 'باز کردن واتس‌اپ',
  visitLocation: 'مسیریابی',
  openWebsite: 'باز کردن وب‌سایت',
  openMap: 'نمایش در نقشه',
  arabic: 'العربية',
  english: 'English',
  languageSelection: 'Language / زبان',
  saveChanges: 'ذخیره تغییرات',
  savedLists: 'علاقه‌مندی‌های من',
  noSaved: 'هنوز کسب و کاری را ذخیره نکرده‌اید. برای ذخیره روی نماد قلب ضربه بزنید.',
  reviews: 'نظرات کاربران',
  writeReview: 'ثبت نظر',
  commentPlaceholder: 'تجربه خود را با دیگران به اشتراک بگذارید...',
  ratingLabel: 'امتیاز',
  submitReview: 'ارسال نظر',
  city: 'شهر',
  area: 'منطقه',
  back: 'بازگشت',
  subcategories: 'زیرشاخه‌ها',
  approvedSuccessfully: 'کسب و کار با موفقیت تایید شد.',
  statusUpdated: 'وضعیت کسب و کار با موفقیت بروزرسانی شد.',
  expiresOn: 'تاریخ انقضا',
  daysLeft: 'روز باقی مانده',
  expiringSoon: 'انقضا به زودی',
  subscriptionExpired: 'انقضای اشتراک',
  allCategories: 'همه دسته‌بندی‌ها'
};

const newFile = file.replace(/};\s*$/g, , fa: \ \n};);
fs.writeFileSync('src/data/translations.ts', newFile);
